services:
  sqlite-mcp-server-py:
    container_name: sqlite_mcp_server_py
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      # The server runs on port 8000 inside the container
      - "8000:8000"
    volumes:
      # Mount the database file. The host path is set by the
      # DB_HOST_PATH environment variable.
      - ${DB_HOST_PATH}:/database/properties.db

    environment:
      # Pass the database path to the application
      - DB_PATH=/database/properties.db
    restart: unless-stopped
    networks:
      - services-network

networks:
  services-network:
    external: true
